<?php
/*珍贵资源 请勿转卖*/
if(!defined('IN_IA')) {
     exit('Access Denied');
}

return array(
    'version'=>'1.0',
    'id'=>'supplychain',
    'name'=>'供应链',
    'v3'=>true,
    'menu'=>array(
        'title'=>'页面',
        'plugincom'=>1,
        'icon'=>'page',
        'items'=>array(
            array(
                'title'=>'入驻申请',
                'route'=>'reg',
                'extends'=>array(
                    'merch.reg.detail'
                ),
                'items'=>array(
                    array(
                        'title'=>'申请中',
                        'param'=>array(
                            'status'=>0
                        )
                    ),
                    array(
                        'title'=>'驳回',
                        'param'=>array(
                            'status'=>-1
                        )
                    )
                )
            ),
            array(
                'title'=>'商户管理',
                'route'=>'user',
                'items'=>array(
                    array(
                        'title'=>'待入驻',
                        'param'=>array(
                            'status'=>0
                        )
                    ),
                    array(
                        'title'=>'入驻中',
                        'param'=>array(
                            'status'=>1
                        )
                    ),
                    array(
                        'title'=>'暂停中',
                        'param'=>array(
                            'status'=>2
                        )
                    ),
                    array(
                        'title'=>'即将到期',
                        'param'=>array(
                            'status'=>3
                        )
                    ),
                    array(
                        'title'=>'已到期',
                        'param'=>array(
                            'status'=>4
                        )
                    ),
                    array(
                        'title'=>'商户分组',
                        'route'=>'group',
                        'route_ns'=>true
                    ),
                    array(
                        'title'=>'商户分类',
                        'route'=>'category',
                        'route_ns'=>true
                    )
                )
            ),
            array(
                'title'=>'数据统计',
                'route'=>'statistics',
                'items'=>array(
                    array(
                        'title'=>'订单统计',
                        'route'=>'order'
                    ),
                    array(
                        'title'=>'商户统计',
                        'route'=>'merch'
                    )
                )
            ),
            array(
                'title'=>'提现申请',
                'route'=>'check',
                'items'=>array(
                    array(
                        'title'=>'待确认申请',
                        'route'=>'status1'
                    ),
                    array(
                        'title'=>'待打款申请',
                        'route'=>'status2'
                    ),
                    array(
                        'title'=>'已打款申请',
                        'route'=>'status3'
                    ),
                    array(
                        'title'=>'无效申请',
                        'route'=>'status_1'
                    )
                ),
                'extends'=>array(
                   'merch.check.detail'
                )
            ),
            array(
                'title'=>'积分提现',
                'route'=>'credit',
                'items'=>array(
                    array(
                        'title'=>'待确认申请',
                        'route'=>'status1'
                    ),
                    array(
                        'title'=>'待打款申请',
                        'route'=>'status2'
                    ),
                    array(
                        'title'=>'已打款申请',
                        'route'=>'status3'
                    ),
                    array(
                        'title'=>'无效申请',
                        'route'=>'status_1'
                    )
                ),
                'extends'=>array(
                    'merch.credit.detail'
                )
            ),
            array(
                'title'=>'其他设置',
                'items'=>array(
                    array(
                        'title'=>'基础设置',
                        'route'=>'set'
                    ),
                    array(
                        'title'=>'通知设置',
                        'route'=>'notice'
                    ),
                    array(
                        'title'=>'入口设置',
                        'route'=>'cover.register',
                        'extends'=>array(
                            'merch.cover.merchlist',
                            'merch.cover.merchuser'
                        )
                    ),
                    array(
                        'title'=>'商户分类幻灯',
                        'route'=>'category.swipe',
                        'extend'=>'merch.category.edit_swipe'
                    )
                )
            )
        )
    ),

    'manage_menu'=>array(
        'home' => array(
            'title'=>'首页',
            'subtitle'=>'供应链首页',
            'icon'=>'store',
        ),
        'goods' => array(
            'title'=>'商品',
            'subtitle'=>'商品管理',
            'icon'=>'goods',
            'items'=>array(
                array(
                    'title'=>'商品列表',
                    'desc'=>'商品管理',
                    'perm'=>'goods.main',
                    'items'=>array(
                        array(
                            'title'=>'出售中',
                            'desc'=>'出售中商品管理',
                            'perm'=>'goods.main'
                        ),
                        array(
                            'title'=>'审核中',
                            'route'=>'check',
                            'desc'=>'审核中商品',
                            'perm'=>'goods.main'
                        ),
                        array(
                            'title'=>'已售罄',
                            'route'=>'out',
                            'desc'=>'已售罄/无库存商品管理',
                            'perm'=>'goods.main'
                        ),
                        array(
                            'title'=>'仓库中',
                            'route'=>'stock',
                            'desc'=>'仓库中商品管理',
                            'perm'=>'goods.main'
                        ),
                        array(
                            'title'=>'回收站',
                            'route'=>'cycle',
                            'desc'=>'回收站/已删除商品管理',
                            'perm'=>'goods.main'
                        ),
                    )
                ),
                array(
                    'title'=>'一键抓取',
//                    'route'=>'virtual',
                    'items'=>array(
                        array(
                            'title'=>'淘宝助手',
                            'route'=>'list',
                            'desc'=>'淘宝助手',
                            'permmust'=>'taobao.list.main'
                        ),
                        array(
                            'title'=>'京东助手',
                            'route'=>'list',
                            'desc'=>'京东助手',
                            'permmust'=>'order.list.main'
                        ),
                        array(
                            'title'=>'1688助手',
                            'route'=>'list',
                            'desc'=>'1688助手',
                            'permmust'=>'order.list.main'
                        ),
                        array(
                            'title'=>'拼多多助手',
                            'route'=>'list',
                            'desc'=>'拼多多助手',
                            'permmust'=>'order.list.main'
                        ),
                    )
                ),
                array(
                    'title'=>'商品类型',
                    'route'=>'category'
                ),
                array(
                    'title'=>'表格导入',
                    'route'=>'tabileimport'
                )
            )
        ),
        'order' => array(
            'title' => '订单',
            'subtitle' => '订单管理',
            'icon' => 'order',
            'items'=> array(
                array(
                    'title'=>'全部订单',
                    'route'=>'list',
                    'desc'=>'全部订单列表',
                    'permmust'=>'order.main'
                ),
                array(
                    'title'=>'待发货',
                    'route'=>'order.status1',
                    'desc'=>'待发货订单管理'
                ),
                array(
                    'title'=>'待收货',
                    'route'=>'order.status2',
                    'desc'=>'待收货订单管理'
                ),
                array(
                    'title'=>'待付款',
                    'route'=>'order.status0',
                    'desc'=>'待付款订单管理'
                ),
                array(
                    'title'=>'已完成',
                    'route'=>'order.status3',
                    'desc'=>'已完成订单管理'
                ),
                array(
                    'title'=>'已关闭',
                    'route'=>'order.status_1',
                    'desc'=>'已关闭订单管理'
                ),
                array(
                    'title'=>'维权',
                    'route'=>'list',
                    'items'=>array(
                        array(
                            'title'=>'维权申请',
                            'route'=>'status4',
                            'desc'=>'维权申请管理'
                        ),
                        array(
                            'title'=>'维权完成',
                            'route'=>'status5',
                            'desc'=>'维权完成管理'
                        )
                    )
                ),
                array(
                    'title'=>'工具',
                    'items'=>array(
                        array(
                            'title'=>'自定义导出',
                            'route'=>'export',
                            'desc'=>'订单自定义导出'
                        ),
                        array(
                            'title'=>'批量发货',
                            'route'=>'batchsend',
                            'desc'=>'订单批量发货'
                        )
                    )
                )
            )
        ),
        'apply' => array(
            'title'=>'账户',
            'subtitle'=>'供应商账户',
            'icon'=>'31',
            'main'=>true,
            'items'=>array(
                array(
                    'title'=>'账户资料',
                    'route'=>'usinfo',
                    'desc'=>'个人资料信息'
                ),
                array(
                    'title'=>'交易设置',
                    'items'=>array(
                        array(
                            'title'=>'微信',
                            'route'=>'wechatpay',
                            'desc'=>'交易设置',
                        ),
                        array(
                            'title'=>'支付宝',
                            'route'=>'alipay',
                            'desc'=>'交易设置',
                        ),
                    )
                )
            )
        ),
        'statistics' => array(
            'title'=>'报表',
            'subtitle'=>'数据统计',
            'icon'=>'statistics',
            'items'=>array(
                array(
                    'title'=>'销售明细',
                    'route'=>'list',
                    'desc'=>'销售明细',
                    'permmust'=>'order.list.main'
                ),
                array(
                    'title'=>'订单统计',
                    'route'=>'list',
                    'desc'=>'订单统计',
                    'permmust'=>'order.list.main'
                )
            )
        ),
        'perm' => array(
            'title'=>'权限',
            'subtitle'=>'权限系统',
            'icon'=>'heimingdan2',
            'items'=>array(
                array(
                    'title'=>'下级操作员列表',
                    'route'=>'user'
                ),
                array(
                    'title'=>'操作员日志',
                    'route'=>'log'
                )
            )
        ),
        'sysset' => array(
            'title'=>'设置',
            'subtitle'=>'供应商设置',
            'icon'=>'sysset',
            'items'=>array(
                array(
                    'title'=>'小票打印机',
                    'items'=>array(
                        array(
                            'title'=>'打印机管理',
                            'route'=>'printer.printer_list',
                            'extends'=>array(
                                'sysset.printer.printer_add'
                            )
                        ),
                        array(
                            'title'=>'打印机模板库',
                            'route'=>'printer'
                        ),
                        array(
                            'title'=>'打印设置',
                            'route'=>'printer.set'
                        )
                    )
                )
            )
        )
    )
);