<?php
 defined("IN_IA") or exit("Access Denied");  
 include "xiwu/Print/HttpClient.class.php";  
 define("USER", "704011699@qq.com");  
 define("UKEY", "e9nTrfZnxr32wZJa");  
 define("IP", "api.feieyun.cn");  
 define("PORT", 80);  
 define("PATH", "/Api/Open/");  
 define("STIME", time());  
 define("SIG", sha1(USER . UKEY . STIME));  
class Xiwulife_scanModuleWxapp extends WeModuleWxapp{ function access_token() { global $_GPC, $_W;  
 $account_api = WeAccount::create();  
 $access_token = $account_api->getAccessToken();  
 return $access_token;  
}  function wp_print($printer_sn, $orderInfo, $times) { $content = array("user" => USER, "stime" => STIME, "sig" => SIG, "apiname" => "Open_printMsg", "sn" => $printer_sn, "content" => $orderInfo, "times" => $times);  
 $client = new HttpClient(IP, PORT);  
if (!$client->post(PATH, $content)) { return "error";  
}else{ return $client->getContent();  
}}  function xiadanddy($item) { global $_GPC, $_W;  
 $dayinlist = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_print") . "WHERE `uniacid` = :uniacid and `default` = 0", array(":uniacid" => $_W["uniacid"]));  
 foreach ($dayinlist as $v) {if ($v["style"] == "58mm") { $orderInfo = $this->test($v["printtype"], $item, 14, 7, 3, 6, "58mm");  
 return $this->wp_print($v["number"], $orderInfo, $v["printnum"]);  
}else{if ($v["style"] == "80mm") { $orderInfo = $this->test($v["printtype"], $item, 26, 7, 4, 6, "80mm");  
 return $this->wp_print($v["number"], $orderInfo, $v["printnum"]);  
}}}}  function jiedan($ordernumber) { global $_GPC, $_W;  
 $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_order") . "WHERE `uniacid` = :uniacid and `ordernumber` = :ordernumber", array(":uniacid" => $_W["uniacid"], ":ordernumber" => $ordernumber));  
if ($item["ordertype"] != 2 || $item["ordertype"] != 1) { pdo_update("xiwu_scan_order", array("status" => 2), array("id" => $item["id"]));  
}else{ pdo_update("xiwu_scan_order", array("status" => 1), array("id" => $item["id"]));  
} $template_id = pdo_fetch("SELECT template_id FROM " . tablename("xiwu_scan_moban") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `mobanid` = 'AT0328'");  
 $template = array("touser" => $item["openid"], "template_id" => $template_id["template_id"], "page" => "bluemoon/pages/details/details?ordernumber=" . $item["ordernumber"], "form_id" => $item["formid"], "data" => array("keyword1" => array("value" => "商家已接单", "color" => "#666666"), "keyword2" => array("value" => date("Y-m-d H:i:s", time()), "color" => "#666666"), "keyword3" => array("value" => "点击查看订单详情", "color" => "#fe0023")));  
 $mobanurl = "https://api.weixin.qq.com/cgi-bin/message/wxopen/template/send?access_token=" . $this->access_token();  
 $moban = ihttp_request($mobanurl, urldecode(json_encode($template)));  
 $text = json_decode($moban["content"], true);  
 $this->xiadanddy($item);  
}  public function store() { global $_GPC, $_W;  
 $data = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_store") . "WHERE `uniacid` = :uniacid", array(":uniacid" => $_W["uniacid"]));  
 $data["logo"] = tomedia($data["logo"]);  
 $data["pics"] = iunserializer($data["pics"]);  
 foreach ($data["pics"] as &$v) {$v = tomedia($v); 
} return $data;  
}  public function user() { global $_GPC, $_W;  
 $data = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_user") . "WHERE `uniacid` =:uniacid AND `openid` = :openid ", array(":uniacid" => $_W["uniacid"], ":openid" => $_W["openid"]));  
 return $data;  
}  public function activity() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_activity") . "WHERE `uniacid` = :uniacid ORDER BY man DESC", array(":uniacid" => $_W["uniacid"]));  
if (count($data) != 0) { $data = $data;  
}else{ $data = false;  
} return $data;  
}  public function czmarketing() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_czmarketing") . "WHERE `uniacid` = :uniacid ORDER BY czpay DESC", array(":uniacid" => $_W["uniacid"]));  
if (count($data) != 0) { $data = $data;  
}else{ $data = false;  
} return $data;  
}  public function parameter() { global $_GPC, $_W;  
 $data = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_parameter") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 $arr = array();  
 $arr[0] = $data["saoma"];  
 $arr[1] = $data["yuyue"];  
 $arr[2] = $data["waimai"];  
 $arr[3] = $data["maidan"];  
 $arr[4] = $data["quhao"];  
 $i = 0;  
 foreach ($arr as $key => $value) {if ($arr[$key] == 0) { $i++;  
}} switch ($i) {case 1: $data["value"] = "100%";  
break;case 2: $data["value"] = "50%";  
break;case 3: $data["value"] = "33.33%";  
break;case 4: $data["value"] = "25%";  
break;case 5: $data["value"] = "20%";  
break;default : $data["value"] = '';  
break;} return $data;  
}  public function doPagestore() { global $_GPC, $_W;  
 $data = $this->store();  
 $data["active"] = $this->activity();  
 $data["parameter"] = $this->parameter();  
 $errno = 0;  
 $message = "首页信息";  
 return $this->result($errno, $message, $data);  
}  public function doPagestorecz() { global $_GPC, $_W;  
 $data = $this->store();  
 $data["active"] = $this->czmarketing();  
 $data["parameter"] = $this->parameter();  
 $errno = 0;  
 $message = "首页信息";  
 return $this->result($errno, $message, $data);  
}  public function doPageparameter() { global $_GPC, $_W;  
 $data = $this->parameter();  
 $errno = 0;  
 $message = "参数设置";  
 return $this->result($errno, $message, $data);  
}  public function doPageadduser() { global $_GPC, $_W;  
 $userlist = $this->user();  
 $user = array("uniacid" => $_W["uniacid"], "nickname" => $_GPC["nickName"], "openid" => $_W["openid"], "avatarUrl" => $_GPC["avatarUrl"]);  
if (!$userlist) { pdo_insert("xiwu_scan_user", $user);  
}else{ pdo_update("xiwu_scan_user", $user, array("openid" => $_W["openid"], "uniacid" => $_W["uniacid"]));  
} $errno = 0;  
 $message = "登录成功";  
 return $this->result($errno, $message, $data);  
}  public function doPageweixinpay() { global $_GPC, $_W;  
if ($_GPC["payment"] == "weixin") { cache_write($_W["openid"], $_GPC["ordernumber"]);  
 $parameter = $this->parameter();  
if ($parameter["wxpaycs"] == 0) { $payprice = 0.01;  
}else{ $payprice = $_GPC["payprice"];  
} $param = array("openid" => $_W["openid"], "fee" => $payprice, "title" => $_GPC["title"], "timeStamp" => time(), "out_trade_no" => $_GPC["ordernumber"]);  
 $data["pay"] = $this->pay($param);  
 $errno = 0;  
 $message = "发起支付";  
 return $this->result($errno, $message, $data);  
}else{if ($_GPC["payment"] == "xianjin") { $arr = array("state" => 2, "payment" => "现金支付", "pricetime" => time());  
 $data = $_GPC["ordernumber"];  
 pdo_update("xiwu_scan_order", $arr, array("ordernumber" => $_GPC["ordernumber"], "uniacid" => $_W["uniacid"]));  
 $errno = 0;  
 $message = "支付成功";  
 return $this->result($errno, $message, $data);  
}else{if ($_GPC["payment"] == "yue") { $arr = array("state" => 1, "payment" => "余额支付", "pricetime" => time());  
 $user = $this->user();  
if (empty($user["password"])) { $errno = 1;  
 $message = "请先开通余额支付";  
 return $this->result($errno, $message, 0);  
}else{if ($_GPC["payprice"] > $user["balance"]) { $errno = 1;  
 $message = "账户余额不足，请先充值";  
 return $this->result($errno, $message, 0);  
}else{if (md5($_GPC["password"]) == $user["password"]) { pdo_update("xiwu_scan_user", array("balance" => floatval($user["balance"]) - floatval($_GPC["payprice"])), array("openid" => $_W["openid"], "uniacid" => $_W["uniacid"]));  
 pdo_update("xiwu_scan_order", $arr, array("ordernumber" => $_GPC["ordernumber"], "uniacid" => $_W["uniacid"]));  
if ($_GPC["ordertype"] == 0) { $title = "扫码点餐（" . $_GPC["tablenumber"] . "）";  
}else{if ($_GPC["ordertype"] == 1) { $title = "预约订单";  
}else{if ($_GPC["ordertype"] == 2) { $title = "外卖订单";  
}else{if ($_GPC["ordertype"] == 3) { $title = "店内买单";  
}else{if ($_GPC["ordertype"] == 4) { $title = "排队取号";  
}else{if ($_GPC["ordertype"] == 5) { $title = "余额充值";  
}}}}}} $arr = array("uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "title" => $title, "time" => time(), "state" => 1, "money" => $_GPC["payprice"]);  
 pdo_insert("xiwu_scan_itemize", $arr);  
 $data = $_GPC["ordernumber"];  
if ($parameter["receipt"] == 1) { $this->jiedan($_GPC["ordernumber"]);  
} $errno = 0;  
 $message = "支付成功";  
 return $this->result($errno, $message, $data);  
}else{ $errno = 1;  
 $message = "密码错误";  
 return $this->result($errno, $message, "001");  
}}}}}}}  public function payResult($params) { global $_GPC, $_W;  
 $arr = array("state" => 1, "payment" => "微信支付", "pricetime" => time());  
if ($params["result"] == "success" && $params["from"] == "notify") { $parameter = $this->parameter();  
 $ordernumber = cache_load($params["user"]);  
 pdo_update("xiwu_scan_order", $arr, array("ordernumber" => $ordernumber, "uniacid" => $_W["uniacid"]));  
 $user = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_user") . "WHERE `uniacid` = :uniacid and `openid` = :openid", array(":uniacid" => $_W["uniacid"], ":openid" => $params["user"]));  
 $order = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_order") . "WHERE `uniacid` = :uniacid and `ordernumber` = :ordernumber", array(":uniacid" => $_W["uniacid"], ":ordernumber" => $ordernumber));  
if ($order["ordertype"] == 5) { $balance = floatval($user["balance"]) + floatval($order["payprice"]);  
 $arr = array("uniacid" => $_W["uniacid"], "openid" => $order["openid"], "title" => "余额充值", "time" => time(), "state" => 0, "money" => $order["payprice"]);  
 pdo_insert("xiwu_scan_itemize", $arr);  
if ($parameter["czmarketing"] == 0) { $czmarketing = $this->czmarketing();  
 foreach ($czmarketing as $key => $value) {if ((floatval($order["payprice"]) >= floatval($value["czpay"]))) { $arr = array("uniacid" => $_W["uniacid"], "openid" => $order["openid"], "title" => "店铺赠送", "time" => time(), "state" => 0, "money" => floatval($value["zspay"]));  
 pdo_insert("xiwu_scan_itemize", $arr);  
 $balance = $balance + floatval($value["zspay"]);  
break;}}} $rel = pdo_update("xiwu_scan_user", array("balance" => $balance), array("openid" => $params["user"], "uniacid" => $_W["uniacid"]));  
}if ($parameter["chongzhi"] == 0) { $jifen = intval($user["jifen"]) + intval($order["payprice"]);  
 pdo_update("xiwu_scan_user", array("jifen" => $jifen), array("openid" => $params["user"], "uniacid" => $_W["uniacid"]));  
}if ($parameter["receipt"] == 1) { $this->jiedan($ordernumber);  
} cache_delete($params["user"]);  
}}  public function doPagecanzhuotitle() { global $_GPC, $_W;  
 $title = pdo_fetch("SELECT title FROM " . tablename("xiwu_scan_program") . "WHERE `uniacid` = :uniacid and `number` = :number", array(":uniacid" => $_W["uniacid"], ":number" => $_GPC["number"]));  
 return $this->result(0, "获取自定义餐桌码", $title["title"]);  
}  public function doPagezjxiaoliang() { global $_GPC, $_W;  
 $orderlistt = json_decode(html_entity_decode($_GPC["orderlist"], ENT_QUOTES), true);  
 $goods = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_goods") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 foreach ($goods as $asd) { foreach ($orderlistt as $v) {if ($asd["id"] == $v["id"]) { $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_goods") . " WHERE `id` = " . $asd["id"]);  
 pdo_update("xiwu_scan_goods", array("sold" => $item["sold"] + $v["num"]), array("id" => $asd["id"]));  
}}} $errno = 0;  
 $message = "增加销量";  
 return $this->result($errno, $message, $orderlistt);  
}  public function doPagesubmitorder() { global $_GPC, $_W;  
if ($_GPC["orderlist"] != '') { $orderlistt = json_decode(html_entity_decode($_GPC["orderlist"], ENT_QUOTES), true);  
 $orderlist = serialize($orderlistt);  
 $data = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_order") . "WHERE `uniacid` = :uniacid ORDER BY id desc LIMIT 1", array(":uniacid" => $_W["uniacid"]));  
 $starttime = mktime(0, 0, 0, date("m"), date("d"), date("Y"));  
if (intval($starttime) > intval($data["time"])) { $qucanma = 1;  
}else{ $qucanma = intval($data["qucanma"]) + 1;  
} $qucanma = sprintf("%03d", $qucanma);  
}else{ $qucanma = '';  
} $trade_no = date("Ymd") . "_" . str_pad(mt_rand(1, 999), 8, "0", STR_PAD_LEFT) . time() . str_pad(mt_rand(1, 999), 2, "0", STR_PAD_LEFT);  
 $parameter = $this->parameter();  
 $resorder = array("uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "nickName" => $_GPC["nickName"], "avatarUrl" => $_GPC["avatarUrl"], "title" => $_GPC["title"], "tablenumber" => $_GPC["tablenumber"], "ordernumber" => $trade_no, "status" => 0, "state" => 0, "payment" => "待支付", "orderlist" => $orderlist, "num" => $_GPC["num"], "scannum" => $_GPC["scannum"], "price" => $_GPC["price"], "payprice" => $_GPC["payprice"], "time" => time(), "ordertype" => $_GPC["ordertype"], "appointday" => $_GPC["appointday"], "appointtime" => $_GPC["appointtime"], "men" => $_GPC["men"], "tel" => $_GPC["tel"], "address" => $_GPC["address"], "receivemoney" => $_GPC["receivemoney"], "pindan" => $_GPC["pindan"], "storediscount" => $_GPC["storediscount"], "carddiscount" => $_GPC["carddiscount"], "remarks" => $_GPC["remarks"], "formid" => $_GPC["formid"], "qucanma" => $qucanma);  
 pdo_update("xiwu_scan_receive", array("state" => 1), array("id" => $_GPC["carddiscountid"]));  
 $rel = pdo_insert("xiwu_scan_order", $resorder);  
 $userlist = $this->user();  
if (!$userlist) { $user = array("uniacid" => $_W["uniacid"], "nickname" => $_GPC["nickName"], "openid" => $_W["openid"], "avatarUrl" => $_GPC["avatarUrl"]);  
 pdo_insert("xiwu_scan_user", $user);  
}if ($rel) { $formidlist = explode(",", $_GPC["formidlist"]);  
if ($formidlist != '') { pdo_delete("xiwu_scan_formid", array("openid" => $_W["openid"]));  
 foreach ($formidlist as $value) { $data = array("uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "formid" => $value, "time" => time());  
 pdo_insert("xiwu_scan_formid", $data);  
}}if ($_GPC["pindan"] == "1") { pdo_delete("xiwu_scan_pindan", array("founder" => $_W["openid"]));  
} $errno = 0;  
 $message = "提交成功";  
}if ($parameter["ljpay"] == 1) {if ($parameter["receipt"] == 1) { $this->jiedan($trade_no);  
}} return $this->result($errno, $message, $trade_no);  
}  public function doPageuser() { global $_GPC, $_W;  
 $data = $this->user();  
 $errno = 0;  
 $message = "用户信息";  
 return $this->result($errno, $message, $data);  
}  public function doPagepassword() { global $_GPC, $_W;  
 $password = md5($_GPC["password"]);  
 pdo_update("xiwu_scan_user", array("password" => $password), array("openid" => $_W["openid"], "uniacid" => $_W["uniacid"]));  
 $errno = 0;  
 $message = "设置支付密码";  
 return $this->result($errno, $message);  
}  public function doPageaddress() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_address") . "WHERE `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}' ORDER BY id DESC");  
 $errno = 0;  
 $message = "收货地址";  
 return $this->result($errno, $message, $data);  
}  public function doPagesubmitaddress() { global $_GPC, $_W;  
 $resorder = array("name" => $_GPC["name"], "tel" => $_GPC["tel"], "xxaddress" => $_GPC["xxaddress"], "addname" => $_GPC["addname"], "lat" => $_GPC["lat"], "lng" => $_GPC["lng"], "address" => $_GPC["address"], "uniacid" => $_W["uniacid"], "openid" => $_W["openid"]);  
if ($_GPC["id"] == '') { $data = pdo_insert("xiwu_scan_address", $resorder);  
 $errno = 0;  
 $message = "提交成功";  
 return $this->result($errno, $message, $data);  
}else{ $data = pdo_update("xiwu_scan_address", $resorder, array("id" => $_GPC["id"]));  
 $errno = 0;  
 $message = "更新成功";  
 return $this->result($errno, $message, $data);  
}}  public function doPagefqpindan() { global $_GPC, $_W;  
 $resorder = array("time" => time(), "uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "founder" => $_W["openid"], "nickName" => $_GPC["nickName"], "avatarUrl" => $_GPC["avatarUrl"]);  
 $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_pindan") . " WHERE `founder` = '{$_W["openid"]}' and `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}'");  
if (empty($item)) { pdo_insert("xiwu_scan_pindan", $resorder);  
}else{ $pindantime = intval($item["time"]) + 3600;  
if ($pindantime < time()) { pdo_delete("xiwu_scan_pindan", array("founder" => $_W["openid"]));  
 pdo_insert("xiwu_scan_pindan", $resorder);  
}else{ pdo_update("xiwu_scan_pindan", $resorder, array("id" => $item["id"]));  
}} $errno = 0;  
 $message = "发起拼单";  
 return $this->result($errno, $message, $resorder);  
}  public function doPagejrpindan() { global $_GPC, $_W;  
 $orderlistt = json_decode(html_entity_decode($_GPC["cart"], ENT_QUOTES), true);  
 $orderlist = serialize($orderlistt);  
 $resorder = array("time" => time(), "uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "founder" => $_GPC["openid"], "nickName" => $_GPC["nickName"], "avatarUrl" => $_GPC["avatarUrl"], "cart" => $orderlist, "price" => $_GPC["price"]);  
 $founder = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_pindan") . " WHERE `openid` = '{$_GPC["openid"]}' and `founder` = '{$_GPC["openid"]}' AND `uniacid` = '{$_W["uniacid"]}'");  
 $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_pindan") . " WHERE `openid` = '{$_W["openid"]}' and `founder` = '{$_GPC["openid"]}' AND `uniacid` = '{$_W["uniacid"]}'");  
if ($founder) {if (!$item) { pdo_insert("xiwu_scan_pindan", $resorder);  
}else{ pdo_update("xiwu_scan_pindan", $resorder, array("id" => $item["id"]));  
} $errno = 0;  
 $message = "加入拼单";  
 return $this->result($errno, $message, $resorder);  
}else{ $errno = 1;  
 $message = "当前拼单已取消";  
 return $this->result($errno, $message, $resorder);  
}}  public function doPagepindanlist() { global $_GPC, $_W;  
 $data["list"] = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_pindan") . " WHERE `founder` = '{$_GPC["openid"]}' and `state` = 0 AND `uniacid` = '{$_W["uniacid"]}'");  
 foreach ($data["list"] as &$v) {if ($v["openid"] == $_W["openid"]) { $v["mee"] = "1";  
}else{ $v["mee"] = "0";  
}if ($v["founder"] == $_W["openid"]) { $aaaa = 1;  
}else{ $aaaa = 0;  
}if ($v["cart"] == null) { $cart = 1;  
}else{ $cart = 0;  
} $v["cart"] = unserialize($v["cart"]);  
} $data["fon"] = $aaaa;  
 $data["cart"] = $cart;  
 $errno = 0;  
 $message = "拼单列表";  
 return $this->result($errno, $message, $data);  
}  public function doPagedeletepindan() { global $_GPC, $_W;  
if ($_GPC["founder"] == 0) { $rel = pdo_delete("xiwu_scan_pindan", array("id" => $_GPC["id"]));  
 $errno = 0;  
 $message = "0删除成功";  
}else{ $rel = pdo_delete("xiwu_scan_pindan", array("founder" => $_W["openid"]));  
 $errno = 0;  
 $message = "1删除成功";  
} return $this->result($errno, $message, $rel);  
}  public function doPagestoredetails() { global $_GPC, $_W;  
 $data["store"] = $this->store();  
 $data["parameter"] = $this->parameter();  
 $goods = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_goods") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 foreach ($goods as &$v) { $v["pic"] = tomedia($v["pic"]);  
 $v["spec"] = json_decode(htmlspecialchars_decode($v["spec"]));  
 $v["pics"] = iunserializer($v["pics"]);  
if (!empty($v["pics"])) { foreach ($v["pics"] as &$value) {$value = tomedia($value); 
} array_unshift($v["pics"], $v["pic"]);  
}else{ $v["pics"][0] = $v["pic"];  
}} $class = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_class") . "WHERE `uniacid` = '{$_W["uniacid"]}' ORDER BY paixu DESC");  
 foreach ($class as &$v) {$v["goods"] = explode(",", $v["goods"]); 
} $data["goods"] = $goods;  
 $data["class"] = $class;  
 $errno = 0;  
 $message = "店铺详情";  
 return $this->result($errno, $message, $data);  
}  public function doPagegoodsdetails() { global $_GPC, $_W;  
 $data = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_goods") . "WHERE `id` = '{$_GPC["thisid"]}'");  
 $data["pic"] = tomedia($data["pic"]);  
 $data["pics"] = iunserializer($data["pics"]);  
if ($data["pics"] != '') { foreach ($data["pics"] as &$v) {$v = tomedia($v); 
}}else{ $data["pics"][0] = $data["pic"];  
} $errno = 0;  
 $message = "商品详情";  
 return $this->result($errno, $message, $data);  
}  public function doPageorder() { global $_GPC, $_W;  
if ($_GPC["orderclass"] == 0) { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_order") . " WHERE `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}' ORDER BY id DESC");  
}else{if ($_GPC["orderclass"] == 1) { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_order") . " WHERE `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}' and `state` = '0' ORDER BY id DESC");  
}else{if ($_GPC["orderclass"] == 2) { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_order") . " WHERE `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}' and `status` = '2' ORDER BY id DESC");  
}else{if ($_GPC["orderclass"] == 3) { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_order") . " WHERE `openid` = '{$_W["openid"]}' AND `uniacid` = '{$_W["uniacid"]}' and `status` = '3' ORDER BY id DESC");  
}}}} $logo = pdo_fetch("SELECT logo FROM " . tablename("xiwu_scan_store") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 foreach ($data as &$v) { $v["pricetime"] = date("Y-m-d H:i:s", $v["pricetime"]);  
 $v["time"] = date("Y-m-d H:i:s", $v["time"]);  
 $v["logo"] = tomedia($logo["logo"]);  
} $errno = 0;  
 $message = "订单列表";  
 return $this->result($errno, $message, $data);  
}  public function doPagestoreindex() { global $_GPC, $_W;  
 $data["tuijian"] = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_goods") . " WHERE `index` = 1 AND `uniacid` = '{$_W["uniacid"]}' ");  
 $data["xiaoliang"] = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_goods") . "WHERE `uniacid` = '{$_W["uniacid"]}' ORDER BY sold DESC LIMIT 0,9");  
 foreach ($data["tuijian"] as &$v) {$v["pic"] = tomedia($v["pic"]); 
} foreach ($data["xiaoliang"] as &$v) {$v["pic"] = tomedia($v["pic"]); 
} $errno = 0;  
 $message = "店铺推荐";  
 return $this->result($errno, $message, $data);  
}  public function doPagedetails() { global $_GPC, $_W;  
 $data["details"] = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_order") . " WHERE `ordernumber` = '{$_GPC["ordernumber"]}' AND `uniacid` = '{$_W["uniacid"]}' ");  
 $data["cardlist"] = pdo_fetchcolumn("SELECT COUNT(*) FROM " . tablename("xiwu_scan_receive") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}' AND `state` = '0' AND `maxmoney` <= '{$data["details"]["payprice"]}'");  
 $data["details"]["orderlist"] = unserialize($data["details"]["orderlist"]);  
 $data["details"]["pricetime"] = date("Y-m-d H:i:s", $data["details"]["pricetime"]);  
 $data["details"]["time"] = date("Y-m-d H:i:s", $data["details"]["time"]);  
 $data["parameter"] = $this->parameter();  
 $data["user"] = $this->user();  
 $errno = 0;  
 $message = "订单详情";  
 return $this->result($errno, $message, $data);  
}  public function doPageorderdetele() { global $_GPC, $_W;  
 $rel = pdo_update("xiwu_scan_order", array("status" => 4), array("ordernumber" => $_GPC["ordernumber"], "uniacid" => $_W["uniacid"]));  
 $errno = 0;  
 $message = "删除订单";  
 return $this->result($errno, $message, $data);  
}  public function doPagecardlist() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_receive") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}' and `state` = 0");  
 foreach ($data as $key => &$v) {if (intval($v["endtime"]) < time()) { pdo_update("xiwu_scan_receive", array("state" => 2, "time" => time()), array("id" => $v["id"]));  
 $v["state"] = 2;  
}}if ($_GPC["stat"] == 0) { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_receive") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}' and `state` = 0");  
}else{ $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_receive") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}' and `state` != 0");  
} foreach ($data as $key => &$v) { $v["time"] = date("Y-m-d H:i:s", $v["time"]);  
 $v["starttime"] = date("Y.m.d", $v["starttime"]);  
 $v["endtime"] = date("Y.m.d", $v["endtime"]);  
} $errno = 0;  
 $message = "优惠券列表";  
 return $this->result($errno, $message, $data);  
}  public function doPagelingqucard() { global $_GPC, $_W;  
if ($_GPC["lingqument"] != '') { $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_card") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `lingqument` = :lingqument", array(":lingqument" => "1"));  
}else{ $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_card") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `lingqument` = :lingqument", array(":lingqument" => "0"));  
} $errno = 0;  
 $message = "领取优惠券列表";  
 return $this->result($errno, $message, $data);  
}  public function doPagewalletlist() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_itemize") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}'");  
 foreach ($data as &$v) {$v["time"] = date("Y-m-d", $v["time"]); 
} $errno = 0;  
 $message = "余额明细";  
 return $this->result($errno, $message, $data);  
}  public function doPagelingqu() { global $_GPC, $_W;  
 $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_card") . "WHERE `uniacid` = :uniacid and `id` = :id", array(":uniacid" => $_W["uniacid"], ":id" => $_GPC["id"]));  
 $cardlist = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_receive") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `openid` = '{$_W["openid"]}'");  
 foreach ($cardlist as $value) {if ($item["id"] == $value["cardid"] && $item["xianzhi"] == 0) { $errno = 1;  
 $message = "领取失败，每人只能领取一次";  
 return $this->result($errno, $message, $data);  
}}if (intval($item["sharemen"]) <= "0") { $errno = 1;  
 $message = "领取失败，当前优惠券暂无库存";  
}else{if ($item["lingqument"] == 1) { $user = $this->user();  
if (intval($user["jifen"]) > intval($item["jifen"])) { $thisjifen = intval($user["jifen"]) - intval($item["jifen"]);  
 pdo_update("xiwu_scan_user", array("jifen" => $thisjifen), array("openid" => $_W["openid"], "uniacid" => $_W["uniacid"]));  
 pdo_update("xiwu_scan_card", array("sharemen" => intval($item["sharemen"]) - 1), array("id" => $_GPC["id"], "uniacid" => $_W["uniacid"]));  
 $data = array("uniacid" => $_W["uniacid"], "nickName" => $_GPC["nickName"], "openid" => $_W["openid"], "money" => $item["price"], "maxmoney" => $item["maxmoney"], "receive" => 1, "cardid" => $item["id"], "starttime" => time(), "endtime" => strtotime($item["endtime"]));  
 $rel = pdo_insert("xiwu_scan_receive", $data);  
if ($rel) { $errno = 0;  
 $message = "领取成功";  
}else{ $errno = 1;  
 $message = "领取失败，请联系管理员";  
}}else{ $errno = 1;  
 $message = "领取失败，积分不足";  
}}else{if ($item["lingqument"] == 0) { pdo_update("xiwu_scan_card", array("sharemen" => intval($item["sharemen"]) - 1), array("id" => $_GPC["id"], "uniacid" => $_W["uniacid"]));  
 $data = array("uniacid" => $_W["uniacid"], "nickName" => $_GPC["nickName"], "openid" => $_W["openid"], "money" => $item["price"], "maxmoney" => $item["maxmoney"], "receive" => 0, "cardid" => $item["id"], "starttime" => time(), "endtime" => strtotime($item["endtime"]));  
 $rel = pdo_insert("xiwu_scan_receive", $data);  
if ($rel) { $errno = 0;  
 $message = "领取成功";  
}else{ $errno = 1;  
 $message = "领取失败，请联系管理员";  
}}}} return $this->result($errno, $message, $data);  
}  public function doPageevaluateimg() { global $_GPC, $_W;  
if ($_FILES["file"] != '') { $Path = "/addons/xiwulife_scan/xiwu/evaluate/" . date("Y-m", time()) . "/";  
 $exename = $this->getExeName($_FILES["file"]["name"]);  
if ($exename != "png" && $exename != "jpg" && $exename != "gif") { return "不允许的扩展名";  
} $fileName = $_SERVER["DOCUMENT_ROOT"] . $Path;  
if (!file_exists($fileName)) { mkdir($fileName, 0777, true);  
} $imageSavePath = $fileName . $_FILES["file"]["name"];  
if (move_uploaded_file($_FILES["file"]["tmp_name"], $imageSavePath)) { $imgurl = $_W["siteroot"] . $Path . $_FILES["file"]["name"];  
 return $imgurl;  
}}}  function getExeName($fileName) { $pathinfo = pathinfo($fileName); return strtolower($pathinfo["extension"]); }  public function doPageevaluatesubmit() { global $_GPC, $_W;  
 $data = array("uniacid" => $_W["uniacid"], "openid" => $_W["openid"], "ordernumber" => $_GPC["ordernumber"], "nickName" => $_GPC["nickName"], "avatarUrl" => $_GPC["avatarUrl"], "evaluateimg" => $_GPC["evaluateimg"], "pingjia" => $_GPC["pingjia"], "time" => time(), "state" => 0);  
 $rel = pdo_insert("xiwu_scan_evaluate", $data);  
if ($rel) {if ($_GPC["ordernumber"] != "store") { pdo_update("xiwu_scan_order", array("evaluatetime" => time(), "evaluate" => $_GPC["pingjia"], "status" => 3), array("ordernumber" => $_GPC["ordernumber"], "uniacid" => $_W["uniacid"]));  
} $errno = 0;  
 $message = "评价成功";  
}else{ $errno = 1;  
 $message = "评价失败，请联系管理员";  
} return $this->result($errno, $message, $data);  
}  public function doPageevaluate() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_evaluate") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `state` = '0' ORDER BY id DESC");  
 foreach ($data as &$v) {if ($v["evaluateimg"] != '') { $v["evaluateimg"] = explode(",", $v["evaluateimg"]);  
} $v["time"] = date("Y-m-d H:i:s", $v["time"]);  
} $errno = 0;  
 $message = "评价列表";  
 return $this->result($errno, $message, $data);  
}  public function doPageservice() { global $_GPC, $_W;  
 $item = pdo_fetch("SELECT * FROM " . tablename("xiwu_scan_parameter") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_order") . "WHERE `uniacid` = '{$_W["uniacid"]}' and `status` = '0' and `state` != '0' ORDER BY id desc");  
 foreach ($data as $k => $value) {if ($item["ljpay"] == 0) {if ($value["state"] != 1) { unset($data[$k]);  
}}else{if ($item["ljpay"] == 1) {if ($value["ordertype"] == 2 && $value["state"] != 1) { unset($data[$k]);  
}}}} $errno = 0;  
 $message = "首次加载消息";  
 return $this->result($errno, $message, $data);  
}  public function doPagemergoods() { global $_GPC, $_W;  
 $data = pdo_fetchall("SELECT * FROM " . tablename("xiwu_scan_goods") . " WHERE `uniacid` = '{$_W["uniacid"]}' ");  
if ($data) { foreach ($data as &$v) {$v["pic"] = tomedia($v["pic"]); 
} $errno = 0;  
 $message = "全部商品";  
}else{ $errno = 1;  
 $message = "商品加载失败";  
} return $this->result($errno, $message, $data);  
}  public function doPagemergoodsstate() { global $_GPC, $_W;  
 $data = pdo_update("xiwu_scan_goods", array("status" => $_GPC["state"]), array("id" => $_GPC["id"], "uniacid" => $_W["uniacid"]));  
if ($data) { $errno = 0;  
 $message = "修改成功";  
}else{ $errno = 1;  
 $message = "修改失败";  
} return $this->result($errno, $message, $data);  
}  function test($printtype, $arr, $A, $B, $C, $D, $style) { global $_GPC, $_W;  
if ($arr["ordertype"] == 0 || $arr["ordertype"] == '') { $ordertype = $arr["tablenumber"];  
}else{if ($arr["ordertype"] == 1) { $ordertype = "预约";  
}else{if ($arr["ordertype"] == 2) { $ordertype = "外卖";  
}else{if ($arr["ordertype"] == 3) { $ordertype = "买单";  
}else{if ($arr["ordertype"] == 4) { $ordertype = "排队";  
}else{if ($arr["ordertype"] == 5) { $ordertype = "充值";  
}}}}}} $title = pdo_fetch("SELECT title FROM " . tablename("xiwu_scan_store") . "WHERE `uniacid` = '{$_W["uniacid"]}'");  
 $orderInfo = "<CB>" . $title["title"] . "#" . $ordertype . "</CB><BR>";  
 $arr["orderlist"] = unserialize($arr["orderlist"]);  
if ($arr["orderlist"] != '') { $orderInfo .= "取餐码：" . $arr["qucanma"] . "<BR>";  
if ($style == "58mm") { $orderInfo .= "名称           单价   数量 金额<BR>";  
 $orderInfo .= "-------------------------------<BR>";  
}else{if ($style == "80mm") { $orderInfo .= "名称                       单价   数量  金额<BR>";  
 $orderInfo .= "---------------------------------------------<BR>";  
}}if ($arr["pindan"] == 0) { foreach ($arr["orderlist"] as $k5 => $v5) {if ($v5["goodtype"] == 0) { $name = $v5["title"];  
 $price = $v5["price"];  
 $num = $v5["num"];  
 $prices = $v5["price"] * $v5["num"];  
 $kw3 = '';  
 $kw1 = '';  
 $kw2 = '';  
 $kw4 = '';  
 $str = $name;  
 $blankNum = $A;  
 $lan = mb_strlen($str, "utf-8");  
 $m = 0;  
 $j = 1;  
 $blankNum++;  
 $result = array();  
 $i = 0;  
if (!($i < $lan)) { $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
while ($i < $lan){ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
continue;}if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}} $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}}}}else{if ($v5["goodtype"] == 1) { foreach ($v5["spec"] as $key => $value) {if (($value["num"] > 0)) { $name = $v5["title"] . "(" . $value["title"] . ")";  
 $price = $value["price"];  
 $num = $value["num"];  
 $prices = $value["price"] * $value["num"];  
 $kw3 = '';  
 $kw1 = '';  
 $kw2 = '';  
 $kw4 = '';  
 $str = $name;  
 $blankNum = $A;  
 $lan = mb_strlen($str, "utf-8");  
 $m = 0;  
 $j = 1;  
 $blankNum++;  
 $result = array();  
 $i = 0;  
if (!($i < $lan)) { $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
while ($i < $lan){ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
continue;}if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}} $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}}}}}}}}}else{ foreach ($arr["orderlist"] as $index => $cart) { $orderInfo .= "#" . $cart["nickname"] . "<BR>";  
 foreach ($cart["cart"] as $k5 => $v5) {if ($v5["goodtype"] == 0) { $name = $v5["title"];  
 $price = $v5["price"];  
 $num = $v5["num"];  
 $prices = $v5["price"] * $v5["num"];  
 $kw3 = '';  
 $kw1 = '';  
 $kw2 = '';  
 $kw4 = '';  
 $str = $name;  
 $blankNum = $A;  
 $lan = mb_strlen($str, "utf-8");  
 $m = 0;  
 $j = 1;  
 $blankNum++;  
 $result = array();  
 $i = 0;  
if (!($i < $lan)) { $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
while ($i < $lan){ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
continue;}if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}} $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}}}}else{if ($v5["goodtype"] == 1) { foreach ($v5["spec"] as $key => $value) {if (($value["num"] > 0)) { $name = $v5["title"] . "(" . $value["title"] . ")";  
 $price = $value["price"];  
 $num = $value["num"];  
 $prices = $value["price"] * $value["num"];  
 $kw3 = '';  
 $kw1 = '';  
 $kw2 = '';  
 $kw4 = '';  
 $str = $name;  
 $blankNum = $A;  
 $lan = mb_strlen($str, "utf-8");  
 $m = 0;  
 $j = 1;  
 $blankNum++;  
 $result = array();  
 $i = 0;  
if (!($i < $lan)) { $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
while ($i < $lan){ $new = mb_substr($str, $m, $j, "utf-8");  
 $j++;  
if (!(mb_strwidth($new, "utf-8") < $blankNum)) { $i++;  
continue;}if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}} $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{if ($m + $j > $lan) { $m = $m + $j;  
 $tail = $new;  
 $lenght = iconv("UTF-8", "GBK//IGNORE", $new);  
 $k = $A - strlen($lenght);  
 $q = 0;  
while ($q < $k){ $kw3 .= " ";  
 $q++;  
} $tail .= $kw3;  
 $head = '';  
 foreach ($result as $value) {$head .= $value; 
}if (strlen($price) < $B) { $k1 = $B - strlen($price);  
 $q = 0;  
while ($q < $k1){ $kw1 .= " ";  
 $q++;  
} $price = $price . $kw1;  
}if (strlen($num) < $C) { $k2 = $C - strlen($num);  
 $q = 0;  
while ($q < $k2){ $kw2 .= " ";  
 $q++;  
} $num = $num . $kw2;  
}if (strlen($prices) < $D) { $k3 = $D - strlen($prices);  
 $q = 0;  
while ($q < $k3){ $kw4 .= " ";  
 $q++;  
} $prices = $prices . $kw4;  
} $orderInfo .= $head . $tail . " " . $price . " " . $num . " " . $prices . "<BR>";  
 @($nums += $prices);  
}else{ $next_new = mb_substr($str, $m, $j, "utf-8");  
if (!mb_strwidth($next_new, "utf-8") < $blankNum) { $m = $i + 1;  
 $result[] = $new . "<BR>";  
 $j = 1;  
} $i++;  
}}}}}}}}}}} $time = date("Y-m-d H:i:s", $arr["time"]);  
if ($style == "58mm") { $orderInfo .= "-------------------------------<BR>";  
}else{if ($style == "80mm") { $orderInfo .= "---------------------------------------------<BR>";  
}}if ($printtype == 0) {if (!($arr["ordertype"] == 0 || $arr["ordertype"] == '')) {if ($arr["ordertype"] == 1) { $orderInfo .= "联系人：" . $arr["men"] . "<BR>";  
 $orderInfo .= "联系电话：" . $arr["tel"] . "<BR>";  
 $orderInfo .= "预约时间：" . $arr["appointday"] . " " . $arr["appointtime"] . "<BR>";  
}else{if ($arr["ordertype"] == 2) { $orderInfo .= "联系人：" . $arr["men"] . "<BR>";  
 $orderInfo .= "联系电话：" . $arr["tel"] . "<BR>";  
 $orderInfo .= "配送地点：" . $arr["address"] . "<BR>";  
 $orderInfo .= "配送费：" . $arr["receivemoney"] . "<BR>";  
}}}if (intval($arr["storediscount"]) != 0 || $arr["storediscount"] != '') { $orderInfo .= "店铺优惠：-" . $arr["storediscount"] . "元<BR>";  
}if (intval($arr["carddiscount"]) != 0 || $arr["carddiscount"] != '') { $orderInfo .= "优惠券：-" . $arr["carddiscount"] . "元<BR>";  
}if (intval($arr["state"]) == 0) { $state = "未付款";  
}else{if (intval($arr["state"]) == 1) { $state = "已付款";  
}} $orderInfo .= "合计：" . $arr["payprice"] . "元(" . $state . ")<BR>";  
} $orderInfo .= "下单时间：" . $time . "<BR>";  
 $orderInfo .= "备注：" . $arr["remarks"] . "<BR>";  
 return $orderInfo;  
}}